from core import *
from repairs import *
from products import *
from returns import *
from comms import *
from diagnostics import *
from parts import *
from comptia import *
from escalations import *
from lookups import *
from orders import *
